# Generated by Django 4.0.4 on 2022-05-31 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuels', '0002_alter_petrol_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Petrol',
            new_name='Fuel',
        ),
    ]
