# Generated by Django 4.0.4 on 2022-06-02 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuels', '0004_fuelstatus_alter_fuel_date_created_alter_fuel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='fuel_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='price',
            field=models.FloatField(default=0, max_length=(15, 2), validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.DeleteModel(
            name='FuelStatus',
        ),
    ]
