# Generated by Django 4.0.4 on 2022-06-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuels', '0006_alter_fuel_fuel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='name',
            field=models.CharField(choices=[('Shell FuelSave Gasoline(unleaded)', 'Shell FuelSave Gasoline(unleaded)'), ('Shell FuelSave Diesel', 'Shell FuelSave Diesel'), ('Shell Diesel Extra', 'Shell Diesel Extra'), ('Shell V-Power', 'Shell V-Power'), ('Shell V-Power NITRO+ Premium Gasoline', 'Shell V-Power NITRO+ Premium Gasoline'), ('Shell E15 Regular 88', 'Shell E15 Regular 88'), ('Shell ClearFLEX E85', 'Shell ClearFLEX E85')], max_length=250, unique=True),
        ),
    ]
