# Generated by Django 4.0.4 on 2022-07-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuels', '0008_alter_fuel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='fuel_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default=1, max_length=8, null=True),
        ),
    ]
