# Generated by Django 4.0.4 on 2022-07-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuels', '0009_alter_fuel_fuel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='fuel_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8, null=True),
        ),
    ]
