# Generated by Django 4.0.4 on 2022-06-03 09:35

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0003_alter_country_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('contact', models.IntegerField(default=0, unique=True, validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(999999999)])),
                ('email', models.EmailField(max_length=50, null=True, unique=True)),
                ('job_type', models.CharField(choices=[('Manager', 'Manager'), ('Cashier', 'Cashier')], max_length=20)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.country')),
            ],
        ),
    ]
