# Generated by Django 4.0.4 on 2022-05-31 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='date_added',
        ),
        migrations.AddField(
            model_name='country',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
