# Generated by Django 4.0.4 on 2022-06-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_remove_country_date_added_country_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(choices=[('Kenya', 'Kenya'), ('Nigeria', 'Nigeria'), ('Tanzania', 'Tanzania')], max_length=25),
        ),
    ]
