# Generated by Django 4.0.4 on 2022-05-18 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='description',
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(999999999), django.core.validators.MaxValueValidator(999999999)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
