# Generated by Django 4.0.4 on 2022-05-30 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('customers', '0002_remove_customer_description_alter_customer_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.country'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
