# Generated by Django 4.0.4 on 2022-05-30 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customerstatus_alter_customer_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customerstatus'),
        ),
    ]
