# Generated by Django 4.0.4 on 2022-05-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstatus',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Guest', 'Guest')], max_length=8),
        ),
    ]
