# Generated by Django 4.0.4 on 2022-06-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customer_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_status',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default=1, max_length=8, null=True),
        ),
    ]
