# Generated by Django 4.0.4 on 2022-06-04 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_delete_customerstatus_remove_customer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Last_name',
            new_name='last_name',
        ),
    ]
