# Generated by Django 4.0.4 on 2022-07-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_alter_customer_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8, null=True),
        ),
    ]
