# Generated by Django 4.0.4 on 2022-06-06 08:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_rename_first_name_customer_first_name_and_more'),
        ('sales', '0002_alter_sale_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.FloatField(max_length=(15, 2), validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='volume',
            field=models.FloatField(max_length=(15, 2)),
        ),
    ]
