# Generated by Django 4.0.4 on 2022-06-08 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_rename_first_name_customer_first_name_and_more'),
        ('sales', '0005_alter_sale_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='name',
            field=models.CharField(choices=[('customer_name', 'customer_name'), ('Nigeria', 'Nigeria'), ('Tanzania', 'Tanzania')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='volume',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
