# Generated by Django 4.0.4 on 2022-06-10 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_alter_customer_customer_status'),
        ('sales', '0006_sale_name_alter_sale_customer_name_alter_sale_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='name',
        ),
        migrations.AddField(
            model_name='sale',
            name='amount_paid',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='balance',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
    ]
