# Generated by Django 4.0.4 on 2022-06-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_remove_sale_name_sale_amount_paid_sale_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='amount_paid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='balance',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
    ]
