# Generated by Django 4.0.4 on 2022-06-14 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_user'),
        ('fuels', '0008_alter_fuel_price'),
        ('sales', '0008_alter_sale_amount_paid_alter_sale_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='fuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuels.fuel'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='served_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
    ]
