# Generated by Django 4.0.4 on 2022-07-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_sale_served_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='served_by',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
